### ISSUE TITLE
Unergonomic API Design

### ISSUE THREAD

**Issue by Cryptex-github** [Tom-the-Bomb/akinator-rs#1]
Hello Mr. Tom,

# Very important issue

I hope such issue finds you well. I am hereby writing to you to inform you about the unfortunate unergonomic API design. It has come to my conclusion that your decision to use blocking HTTP client for said library does not meet real life use cases, such includes but is not limited to Discord bots, webapp, among numerous more use cases where async would be beneficial. Not only does it brings performance increases, it also allows other tasks to be executed concurrently. In conclusion, I highly recommend you make use of async. If you encountered any issue in the process of doing such, please let me know, I give thanks Tom.

**Comment by jay3332** [comment]
unergonomic*

**Comment by Cryptex-github** [comment]
> unergonomic*

Dear Jay3332,
I give thanks for your correction.

**Comment by Tom-the-Bomb** [comment]
for sure
